In [4]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_df = pd.read_csv('/home/dans/Downloads/pyp/py2/movies.csv')
movies_df

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [3]:
#columns i need
impColumns = ['genres','title','keywords','cast','director', 'tagline']

In [4]:
#replacing null values with null strings
for column in impColumns:
    movies_df[column] = movies_df[column].fillna('')

In [5]:
selectColumns = movies_df['title']+""+movies_df['genres']+""+movies_df['cast']+""+movies_df['director']+''+movies_df['tagline']

selectColumns

0       AvatarAction Adventure Fantasy Science Fiction...
1       Pirates of the Caribbean: At World's EndAdvent...
2       SpectreAction Adventure CrimeDaniel Craig Chri...
3       The Dark Knight RisesAction Crime Drama Thrill...
4       John CarterAction Adventure Science FictionTay...
                              ...
4798    El MariachiAction Crime ThrillerCarlos Gallard...
4799    NewlywedsComedy RomanceEdward Burns Kerry Bish...
4800    Signed, Sealed, DeliveredComedy Drama Romance ...
4801    Shanghai CallingDaniel Henney Eliza Coupe Bill...
4802    My Date with DrewDocumentaryDrew Barrymore Bri...
Length: 4803, dtype: object

In [6]:
#vectorizer 
vectorizer = TfidfVectorizer()

vectorizedColumns = vectorizer.fit_transform(selectColumns)
print(vectorizedColumns)

  (0, 1579)	0.3159089827840997
  (0, 471)	0.1252710080858573
  (0, 8582)	0.1542786163059702
  (0, 22135)	0.1223441000082608
  (0, 9057)	0.28295559086577904
  (0, 27722)	0.27085473564886126
  (0, 28136)	0.22967130738822358
  (0, 21762)	0.24859166898475477
  (0, 22834)	0.24859166898475477
  (0, 27002)	0.22654203857915542
  (0, 23689)	0.19183396188044208
  (0, 14511)	0.26605242546336505
  (0, 16836)	0.18369485834004942
  (0, 20967)	0.3159089827840997
  (0, 3701)	0.3159089827840997
  (0, 24564)	0.06529883698781792
  (0, 27702)	0.1606352547425141
  (0, 18409)	0.09478605923523362
  (0, 18811)	0.29098070412373234
  (1, 471)	0.1026748303159299
  (1, 8582)	0.1264500940212382
  (1, 24564)	0.21408136200058867
  (1, 27702)	0.2633202650072047
  (1, 18409)	0.15537741249153436
  (1, 19418)	0.22199840528107426
  :	:
  (4801, 19037)	0.1961198489162683
  (4801, 11603)	0.26086187571990255
  (4801, 705)	0.1691887300748159
  (4801, 7819)	0.22665731415175447
  (4801, 22511)	0.4899153206058952
  (4801, 28100)	0.26086187571990255
  (4801, 3675)	0.27348576168683925
  (4801, 5405)	0.27348576168683925
  (4801, 21552)	0.27348576168683925
  (4801, 22678)	0.27348576168683925
  (4801, 12352)	0.27348576168683925
  (4801, 27934)	0.27348576168683925
  (4802, 6116)	0.23938379455613634
  (4802, 27544)	0.1558593712994948
  (4802, 3187)	0.18880743981644685
  (4802, 8031)	0.18819447168449713
  (4802, 5305)	0.23681730243044657
  (4802, 1971)	0.21042302411726105
  (4802, 20880)	0.18528252237657822
  (4802, 17661)	0.18759216441005913
  (4802, 10744)	0.2421558172278254
  (4802, 8815)	0.25211876388784304
  (4802, 7353)	0.30420766448880737
  (4802, 11697)	0.6084153289776147
  (4802, 7496)	0.30420766448880737

In [5]:
#cosine similarity scores of the data
similarity = cosine_similarity(vectorizedColumns)
similarity.shape

NameError: name 'vectorizedColumns' is not defined

In [8]:
#getting user movie choice
userMovie = input("enter movie name:")

enter movie name: avatar

In [14]:
#create a list of all the movies in the dataste 
moviesList = movies_df['title'].tolist()

In [15]:
# compare the movie name provided by the user to one in the dataset to find the closest match using difflib
getCloseMatch = difflib.get_close_matches(userMovie, moviesList)
matchedMovies = getCloseMatch[0]
matchedMovies

'Avatar'

In [16]:
#Find the index of the matched movie on the dataset
matchedMovieIndex = movies_df[movies_df.title == matchedMovies]['index'].values[0]
matchedMovieIndex

0

In [7]:
# Get a list of similar movies using the cosine similarity and the index of the matched movies
similarity_score = list(enumerate(similarity[matchedMovieIndex]))

NameError: name 'similarity' is not defined

In [6]:
#sort the movies from highest  similarity score to lowest
sortedMovies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

NameError: name 'similarity_score' is not defined